---
# tasks file for haproxy

- name: publish MySQL endpoint
  set_fact:
    mysql_endpoints:
      - "mysql+pymysql://127.0.0.1:200/"

- name: store facts
  blockinfile:
    dest: /tmp/output-facts.yaml
    create: yes
    block: |
      mysql_endpoints:
        {% for endpoint in mysql_endpoints %}- {{ endpoint }}{% endfor %}

- name: gather facts
  fetch:
    src: /tmp/output-facts.yaml
    dest: "fetched-facts/{{ fact_prefix }}"
