#!/usr/bin/env python
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

'''
Merge yaml files into one by making a list of entries when an
entry is already existing.
'''

import os
import sys
import yaml

def main():
    # first arg is the top directory
    # other args are the file names to process
    
    merged = {}
    for fname in sys.argv[2:]:
        fp = open(fname)
        content = yaml.load(fp)
        fp.close()
        for key in content:
            if key in merged:
                merged[key] = merged[key] + content[key]
            else:
                merged[key] = content[key]
    output_fname = os.path.join(sys.argv[1], 'merged.yaml')
    outp = open(output_fname, 'w')
    outp.write(yaml.dump(merged))
    outp.close()
    print output_fname

if __name__ == "__main__":
    main()

# merge ends here
